# Generated by Django 3.0.6 on 2020-05-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='item_duration_ms',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
