version: "3.8"
services:
  django:
    init: true
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "80:8000"
    environment:
      PYTHONBREAKPOINT: ipdb.set_trace
  scheduler:
    init: true
    build: .
    volumes:
      - .:/usr/src/app
    command: scheduler
