version: "3.7"
services:
  go:
    build: .
    command: gowatch
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
  dynamodb:
    init: true
    image: amazon/dynamodb-local:latest
